### ISSUE TITLE
please add osx_arm64

### ISSUE THREAD

**Issue by kadaliao** [conda-forge/powerline-status-feedstock#18]
Dear Maintainers,

First, thank you for your excellent work on maintaining this package! It has been incredibly helpful for many users, including myself.

I would like to kindly request the addition of support for the osx-arm64 platform. With the growing popularity of Apple Silicon devices, having a dedicated build for this platform would greatly benefit users running on these systems.

Thank you for your time and consideration.

**Comment by synapticarbors** [comment]
Started the process in https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/6828

**Comment by synapticarbors** [comment]
Completed by #19
